### ISSUE TITLE
new submodule

### ISSUE THREAD

**Issue by questor** [ggnkua/Atari_ST_Sources#1]
something you can link in as a submodule, it's from bitmaster a windows-editor for tfmx: 
https://github.com/Dunkelwind/ym

**Comment by ggnkua** [comment]
That looks neat but does it contain any atari code?

**Comment by questor** [comment]
not directly :) atari-related because as far as I understood it's an editor for the mad-max player

**Comment by ggnkua** [comment]
I'm still unsure about this. This is a Atari-only repository so where does one draw the line? If I add this do I add Steem engine/hatari/ostis/etc sources? Or every other C program from the 80s that can be compiled to Atari ST? I'll have to think about this....
