### ISSUE TITLE
CPU_MOD, Essay and other sources by Patrick Ruiz

### ISSUE THREAD

**Issue by mikrosk** [ggnkua/Atari_ST_Sources#11]
Once upon a time I'd managed to contact Patrick Ruiz. He was very kind to release his CPU_MOD sources to public, in fact, he sent me all of his projects. Unfortunately I lost my mailbox from that time. Accidentaly, I found an old backup and voila! The most precise Atari MOD player's source code is not lost anymore! :)

Attaching as a ZIP because I'm not sure how / what you would like to copy.

[ruiz.zip](https://github.com/ggnkua/Atari_ST_Sources/files/4644796/ruiz.zip)

**Comment by ggnkua** [comment]
Done, thanks for the sources!
