### ISSUE TITLE
New possible submodules...

### ISSUE THREAD

**Issue by kollokollo** [ggnkua/Atari_ST_Sources#12]
I have put together some repositories with ATARI ST sources (from the 1990th):

https://codeberg.org/kollo/Convert3-ST

https://codeberg.org/kollo/Vt100emu-ST
(this is already in, and it used to be included as submodule, sorry for having moved this to codeberg).

https://codeberg.org/kollo/Sp-Sek-ST

https://codeberg.org/kollo/Atomuhr-ST

maybe you war to add them.

**Comment by ggnkua** [comment]
Hi Markus,

Cool, thanks very much for the links! Good timing too - I was in the process of adding another submodule I came across today.

Also: don't worry or feel guilty about moving your repos around for my sake. I don't ask people before adding their repos to mine anyway so I don't have any demands about maintaining the repos should they change their minds. As always: this is all for fun!

Wishes for a happy 2021!

**Comment by kollokollo** [comment]
Here is another one: 

https://codeberg.org/kollo/R-Disk-ST

**Comment by ggnkua** [comment]
Added, thanks!
