### ISSUE TITLE
amidilib is down

### ISSUE THREAD

**Issue by maraflush** [ggnkua/Atari_ST_Sources#14]
Hello,

I think you can remove these lines : the repo removed :
```
[submodule "C/Paweł Góralski n0kturnal/amidilib"]^M
        path = C/Paweł Góralski n0kturnal/amidilib^M
        url = https://github.com/n0kturnal/amidilib.git^M
```

**Comment by ggnkua** [comment]
Hi, thanks for the report, I replaced the submodule with the actual files, just for posterity.

Merry Christmas!

**Comment by maraflush** [comment]
Merci GGN,

Merry Christmas to you too !
