### ISSUE TITLE
sonolumineszenz as submodule

### ISSUE THREAD

**Issue by mikrosk** [ggnkua/Atari_ST_Sources#9]
https://github.com/ggnkua/Atari_ST_Sources/tree/master/ASM/Tat/sonodata
https://github.com/ggnkua/Atari_ST_Sources/tree/master/ASM/Tat/sonodsp
https://github.com/ggnkua/Atari_ST_Sources/tree/master/ASM/Tat/sonosrc

can be replaced with a submodule pointing to:

https://github.com/tattlemuss/sonolumineszenz

**Comment by ggnkua** [comment]
Done (although submodules make me nervous)
